version: '3'
services:
  test_db:
    container_name: test_db_image_XML
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=UTC
    volumes:
      - ./:/table
